# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 779b5364caef1040f205e49dc0bd298d66292baeaf3984fa444ec7c88c7522799b7de1e138a3718fb1b296ec15babf9d744efa5cba5668cce415f73abec7d22a

test:
  secret_key_base: 2b23dce25df4cc5e9aa309c552a406a01a780a561b24a6cac8b9d9c99ae5be6bcde906b8425757d16824cd371136aefe6c27d611075a5124acd17a5fe982ac29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
